### ISSUE TITLE
rtp bin with flvmux does not produce a usable video file

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#297] opened 2016-06-14 08:36 UTC
With the profile below (using rtp bin and flvmux), galicaster 2.x beta1 does not produce a usable flv video file. The flv should be 60s long but does not play back correctly in vlc, and Opencast workflow operations on it fail.

Sample flv from an Axis 1428 IP camera:

https://drive.google.com/open?id=0B9bczAl3ucCVQnh0XzQ0VFZRX00

The same configuration worked successfully in gc 1.x.

[track1]
name = audio
device = pulse
flavor = presenter
location = alsa_input.usb-Burr-Brown_from_TI_USB_audio_CODEC-00.analog-mono
file = audio.flac
vumeter = True
amplification = 1.0
player = True
audioencoder = deinterleave name=d d.src_0 ! audioconvert ! flacenc
active = True
delay = 0.2

[track2]
name = presenter
device = rtp
flavor = presenter
location = rtspt://137.158.32.75/stream
file = presenter.flv
cameratype = h264
audio = False
muxer = flvmux
active = True

**Comment by hcaloto** [comment] 2016-06-14 10:02
Hi Stephen, 

Could you run the following sentence in a command line?

`gst-launch-1.0 -e rtspsrc location=rtspt://137.158.32.75/stream ! rtph264depay ! h264parse ! queue ! flvmux ! queue ! filesink async=false location=/tmp/a.flv`

After a few seconds, press CTRL+C in order to close connection, and then try to reproduce the resulting video (/tmp/a.flv). Please let us know if this is a valid video file.

Thank you!

**Comment by smarquard** [comment] 2016-06-14 10:53
No, that doesn't work either, i.e. the flv file is not playable. I also tried "mp4mux" to create an mp4 and that also doesn't work.

**Comment by bleedinge** [comment] 2016-06-14 11:07
@smarquard, is there any chance you can provide us with a mp4 file for a previous recording from this same camera, maybe from Galicaster 1.x?

**Comment by smarquard** [comment] 2016-06-14 11:27
In this folder are the results of that gstreaer pipeline with gstreamer 0.10, 1.2.1, and 1.8.1. It works in 0.10 and 1.21, and fails in 1.8.1 (the camera used to test 0.10 and 1.2.1 is the same, and a different camera though same make and configuration for 1.8.1). I don't think it's the camera though, as these tests are with a Vaddio, and it also fails with an Axis 1428.

https://drive.google.com/open?id=0B9bczAl3ucCVR2tETEtwaF9KdDA

**Comment by smarquard** [comment] 2016-06-14 11:43
These two pipelines work fine with gstreamer 1.8.1 (adapted from http://stackoverflow.com/questions/25840509/how-to-save-a-rtsp-video-stream-to-mp4-file-via-gstreamer)

gst-launch-1.0 -e rtspsrc location=rtspt://137.158.32.75/stream ! decodebin ! x264enc ! mp4mux ! filesink location=/tmp/vaddio-gst-1.8.1.mp4

gst-launch-1.0 -e rtspsrc location=rtspt://137.158.32.75/stream ! decodebin ! x264enc ! flvmux ! filesink location=/tmp/vaddio-gst-1.8.1-new.flv

**Comment by bleedinge** [comment] 2016-06-27 12:10
It looks like this issue can be solved specifying the stream URL with an uri like this **rtsp://137.158.32.75/stream** instead of rtspt://137.158.32.75/stream, so this means gstreamer 1.0 won't work with RTSP over TCP properly in this particular pipeline.

Closing this issue, as this can be solved just by replacing the URL in the profile.

**Closed by bleedinge** 2016-06-27 12:10 UTC
Labels: P2: Release blocker, question

**Comment by devangovender** [comment] 2016-06-29 12:45
At UCT rtspt is needed for correct av sync.
