### ISSUE TITLE
Problem with scheduled recordings.

### ISSUE THREAD

**Issue by maruiz93** [teltek/Galicaster#227] opened 2016-05-19 13:34 UTC
When a recording is scheduled, Galicaster usually breaks when starting or when ending the recording.

Some of the error given are:

*  gtk_css_value_inherit_free
* Segmentation fault
* cairo_surface_destroy
* _gtk_css_number_value_get

**Comment by devangovender** [comment] 2016-06-02 10:18
Galicaster 2 (beta) still seems to have this issue. Galicaster UI crashes at the end of the scheduled recording with the following errors:

ERROR   recorder        gst-stream-error-quark: Internal data flow error. (1) (gstqueue.c(986): gst_queue_handle_sink_event): /GstPipeline:galicaster_recorder/galicaster+recorder+bins+pulse+GCpulse:galicaster+recorder+bins+pulse+gcpulse0/GstBin:bin0/GstQueue:queue2: streaming task paused, reason not-linked (-1))

ERROR   service Handle error (gst-stream-error-quark: Internal data flow error. (1) (gstqueue.c(986): gst_queue_handle_sink_event): /GstPipeline:galicaster_recorder/galicaster+recorder+bins+pulse+GCpulse:galicaster+recorder+bins+pulse+gcpulse0/GstBin:bin0/GstQueue:queue2: streaming task paused, reason not-linked (-1)))

**Comment by maruiz93** [comment] 2016-06-02 14:18
Could you tell us which profile are you using?
The issues we were having with scheduled recording were eventual, is this issue eventual too, or can you always reproduce it?

**Comment by devangovender** [comment] 2016-06-02 15:05
Galicaster always crashes at the end of a recording. This is the profile configuration we are using:

[track1]
name = audio
device = pulse
flavor = presenter
location = alsa_input.usb-Burr-Brown_from_TI_USB_audio_CODEC-00.analog-mono
file = audio.flac
vumeter = True
amplification = 1.0
player = True
audioencoder = deinterleave name=d d.src0 ! audioconvert ! flacenc
active = True
delay = 0.3

[track2]
name = presenter
device = rtp
flavor = presenter
location = rtspt://137.158.32.75/stream
file = presenter.flv
cameratype = h264
audio = False
muxer = flvmux
active = True

[track3]
name = presentation
device = v4l2
flavor = presentation
location = /dev/dada0
file = presentation.avi
caps = video/x-raw,format=YUY2,framerate=25/1,width=1280,height=720
active = True

**Comment by hcaloto** [comment] 2016-06-09 14:48
It seems like we have two different issues, the first one is a crash that closes Galicaster. The other one is an error in the profile when stopping a recording.

Firstly, we are going to test the first one because it is blocker for the next beta release. Then we will try to fix the second one.

So, Silvia could you please test if there is a segmentation fault related with scheduled recordings by using any profile?

**Comment by silviabf** [comment] 2016-06-10 09:24
The first bug is solved in version beta2. There is no error in scheduled recordings. I leave open this issue to resolve the second bug.

**Comment by silviabf** [comment] 2016-06-10 11:27
I reproduced the second bug with the attached profile.
[rtp.ini.txt](https://github.com/teltek/Galicaster/files/308881/rtp.ini.txt)

**Comment by hcaloto** [comment] 2016-06-13 10:27
We have the first bug solved, the second one seems to be a mistake in the profile, because inspecting the element deinterleave I saw that:

`
Pad Templates:
  SRC template: 'src_%u'
    Availability: Sometimes
`

So in the profile should be **"src_0"** instead of **"src0"**

**Comment by bleedinge** [comment] 2016-06-13 12:37
@smarquard, @devangovender can you please test it?

With the change suggested by @hcaloto we have your sample profile working ok here.

**Comment by smarquard** [comment] 2016-06-13 12:55
That seems to fix it. For the record, we changed:

audioencoder = deinterleave name=d d.src0 ! audioconvert ! flacenc

to

audioencoder = deinterleave name=d d.src_0 ! audioconvert ! flacenc

These 2 messages do show on the console, but I'm guessing they're not specifically related to this issue:

** (run_galicaster.py:4041): CRITICAL **: gst_v4l2_buffer_pool_process: assertion 'gst_buffer_pool_is_active (bpool)' failed

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by silviabf** [comment] 2016-06-13 15:20
I tested it here, and with this change the profile works correctly.
This message in console: "Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged." happens always (but it does not depend of the profile).

I close this issue. Thanks @smarquard and @devangovender!

**Closed by silviabf** 2016-06-13 15:20 UTC
Labels: bug, Ready for QA, Release blocker
