### ISSUE TITLE
Incorrect elapsed time for scheduled recording

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#301] opened 2016-06-14 11:17 UTC
Latest 2.0.x code

Schedule a 1min recording on Opencast

GC 2.x starts recording. At the end, the duration is shown as "Elapsed time: 00:00" in the recorder UI, and 0:00 Duration in the media manager.

Durations are shown as 0 in the manifest.xml

```
 <media>
      <track id="track-0" type="presenter/source">
         <tags>
            <tag>archive</tag>
         </tags>
         <mimetype>audio/flac</mimetype>
         <url>audio.flac</url>
         <duration>0</duration>
      </track>
      <track id="track-1" type="presenter/source">
         <tags>
            <tag>archive</tag>
         </tags>
         <mimetype>video/avi</mimetype>
         <url>presentation.avi</url>
         <duration>0</duration>
      </track>
   </media>
```

A manual recording from the Galicaster UI works fine.

This is a simple profile with audio and datapath only
```
[track1]
name = audio
device = pulse
flavor = presenter
location = alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo
file = audio.flac
vumeter = True
amplification = 1.0
player = True
audioencoder = deinterleave name=d d.src_0 ! audioconvert ! flacenc
active = True
delay = 0.2

[track2]
name = presentation
device = v4l2
flavor = presenter
location = /dev/video0
file = presentation.avi
caps = video/x-raw,format=YUY2,framerate=25/1,width=1280,height=720
active = True
```

These logs are shown on the console

(run_galicaster.py:12929): GStreamer-WARNING **: gstpad.c:5052:store_sticky_event:<flacenc0:src> Sticky event misordering, got 'segment' before 'caps'

(run_galicaster.py:12929): GStreamer-WARNING **: gstpad.c:5052:store_sticky_event:<queue3:sink> Sticky event misordering, got 'segment' before 'caps'

(run_galicaster.py:12929): GStreamer-WARNING **: gstpad.c:5052:store_sticky_event:<queue3:src> Sticky event misordering, got 'segment' before 'caps'

(run_galicaster.py:12929): GStreamer-WARNING **: gstpad.c:5052:store_sticky_event:<gc-audio-sink:sink> Sticky event misordering, got 'segment' before 'caps'

** (run_galicaster.py:12929): CRITICAL **: gst_v4l2_buffer_pool_process: assertion 'gst_buffer_pool_is_active (bpool)' failed

though I don't think they're specific to this issue (manual recording fine, scheduled recording fails).

**Comment by hcaloto** [comment] 2016-06-15 13:58
Hi Stephen, I have tested with Opencast 1.x and 2.x and I am not able to reproduce the issue.

I have used the same profile as yours, except the audio location. In your case, does it happen for all scheduled recordings? Can you playback this recordings?

Thank you

**Comment by smarquard** [comment] 2016-06-16 07:56
It happened for every recording (on our "em7" CA). The recording wasn't usable. I'll see if I can test more tomorrow.

**Comment by silviabf** [comment] 2016-06-17 11:10
Hi @smarquard , I am trying to replicate this issue, with this profile (only changes the location and the caps of presentation):
```
[track1]
name = presentation
device = v4l2
flavor = presenter
location = /dev/screen
file = presentation.avi
caps = video/x-raw,format=YUY2,framerate=30/1,width=1024,height=768
active = True

[track2]
name = audio
device = pulse
flavor = presenter
location = default
file = audio.flac
vumeter = True
amplification = 1.0
player = True
audioencoder = deinterleave name=d d.src_0 ! audioconvert ! flacenc
active = True
delay = 0.2
```
and i always have the correct duration in the manifest.xml in the scheduled recordings. I found this other issue #317 when i test this. Could you test that the duration problem is no related with this other issue?, you only have to switch the order of the tracks in the profile. 
Thank you.

**Comment by smarquard** [comment] 2016-06-17 11:30
Hi @silviabf, so far I haven't been able to reproduce the original issue in testing on the same CA, but did run into #316. I'm continuing to test and will also test with the tracks swapped around as you suggest.
Thanks

**Comment by silviabf** [comment] 2016-06-17 12:00
Hi @smarquard , then I close this issue, feel free to open the issue again if you can replicate the problem again.

**Closed by silviabf** 2016-06-17 12:00 UTC
Labels: bug, Release blocker
