### ISSUE TITLE
X Window System error.

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#316] opened 2016-06-17 08:57 UTC
This happened at the end of a 1 minute scheduled recording, latest 2.0.x code

(run_galicaster.py:9018): Gdk-ERROR **: The program 'run_galicaster.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadColor (invalid Colormap parameter)'.
  (Details: serial 282173 error_code 12 request_code 1 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
/usr/bin/galicaster: line 36:  9018 Trace/breakpoint trap   python /usr/share/galicaster/run_galicaster.py

**Comment by smarquard** [comment] 2016-06-17 08:58
Here is the galicaster log. It looks like the error was possibly triggered by the ingest operation (although previous ingests worked fine).

galicaster      2016-06-17 10:54:51,091 DEBUG   heartbeat       galicaster-notify-short in 10
galicaster      2016-06-17 10:54:59,783 INFO    scheduler       Start record 56448828, duration 60000 ms
galicaster      2016-06-17 10:54:59,784 INFO    service Recording (current status: preview)
galicaster      2016-06-17 10:54:59,786 DEBUG   repository      Temporal data saved to /usr/share/galicaster-repository/rectemp/info.json
galicaster      2016-06-17 10:55:01,092 INFO    scheduler       Set status capturing to server
galicaster      2016-06-17 10:55:01,092 INFO    client  Sending state capturing
galicaster      2016-06-17 10:55:01,104 INFO    conf    Be careful using profiles and opencast scheduler
galicaster      2016-06-17 10:55:01,119 DEBUG   heartbeat       galicaster-notify-short in 10
galicaster      2016-06-17 10:55:11,119 INFO    scheduler       Set status capturing to server
galicaster      2016-06-17 10:55:11,120 INFO    client  Sending state capturing
galicaster      2016-06-17 10:55:11,131 INFO    conf    Be careful using profiles and opencast scheduler
galicaster      2016-06-17 10:55:11,146 DEBUG   heartbeat       galicaster-notify-short in 10
galicaster      2016-06-17 10:55:20,812 INFO    scheduler       Proccess ical
galicaster      2016-06-17 10:55:20,835 INFO    client  iCal modified
galicaster      2016-06-17 10:55:20,836 DEBUG   scheduler       Creating MP with UID 56448828 from ical
galicaster      2016-06-17 10:55:20,837 DEBUG   heartbeat       galicaster-notify-long in 60
galicaster      2016-06-17 10:55:21,147 INFO    scheduler       Set status capturing to server
galicaster      2016-06-17 10:55:21,147 INFO    client  Sending state capturing
galicaster      2016-06-17 10:55:21,160 INFO    conf    Be careful using profiles and opencast scheduler
galicaster      2016-06-17 10:55:21,177 DEBUG   heartbeat       galicaster-notify-short in 10
galicaster      2016-06-17 10:55:31,178 INFO    scheduler       Set status capturing to server
galicaster      2016-06-17 10:55:31,178 INFO    client  Sending state capturing
galicaster      2016-06-17 10:55:31,188 INFO    conf    Be careful using profiles and opencast scheduler
galicaster      2016-06-17 10:55:31,203 DEBUG   heartbeat       galicaster-notify-short in 10
galicaster      2016-06-17 10:55:41,203 INFO    scheduler       Set status capturing to server
galicaster      2016-06-17 10:55:41,203 INFO    client  Sending state capturing
galicaster      2016-06-17 10:55:41,214 INFO    conf    Be careful using profiles and opencast scheduler
galicaster      2016-06-17 10:55:41,228 DEBUG   heartbeat       galicaster-notify-short in 10
galicaster      2016-06-17 10:55:51,229 INFO    scheduler       Set status capturing to server
galicaster      2016-06-17 10:55:51,229 INFO    client  Sending state capturing
galicaster      2016-06-17 10:55:51,238 INFO    conf    Be careful using profiles and opencast scheduler
galicaster      2016-06-17 10:55:51,252 DEBUG   heartbeat       galicaster-notify-short in 10
galicaster      2016-06-17 10:55:59,784 INFO    scheduler       Stop record 56448828
galicaster      2016-06-17 10:55:59,784 INFO    service Stopping the capture
galicaster      2016-06-17 10:55:59,784 DEBUG   recorder        Stopping recorder, sending EOS event to sources
galicaster      2016-06-17 10:55:59,791 DEBUG   recorder        EOS message successfully received
galicaster      2016-06-17 10:55:59,844 INFO    service Adding new mediapackage (56448828) to the repository
galicaster      2016-06-17 10:55:59,846 INFO    repository      Repository temporal files removed
galicaster      2016-06-17 10:55:59,846 INFO    worker  Creating Ingest Job for MP 56448828
galicaster      2016-06-17 10:55:59,849 INFO    service Starting recording service in the preview status
galicaster      2016-06-17 10:55:59,850 INFO    worker  Executing Ingest for MP 56448828
galicaster      2016-06-17 10:55:59,850 DEBUG   service Using Default profile
galicaster      2016-06-17 10:55:59,850 DEBUG   recorder        Init bin audio galicaster.recorder.bins.pulse
galicaster      2016-06-17 10:55:59,851 DEBUG   utils   Audio sink: sink-audio -> alsasink
galicaster      2016-06-17 10:55:59,852 INFO    worker  Zipping MP 56448828 to /tmp/tmpesGR6f
galicaster      2016-06-17 10:55:59,852 DEBUG   serializer      Using System Zip
galicaster      2016-06-17 10:55:59,854 DEBUG   recorder        Init bin presenter galicaster.recorder.bins.rtp
galicaster      2016-06-17 10:55:59,856 DEBUG   utils   Video sink: sink-presenter -> xvimagesink
galicaster      2016-06-17 10:55:59,857 DEBUG   utils   Audio sink: sink-audio-presenter -> alsasink
galicaster      2016-06-17 10:55:59,870 INFO    client  Ingesting MP 56448828 to Server http://media.uct.ac.za

**Comment by silviabf** [comment] 2016-06-17 13:44
I replicated this issue. I discard that the problem is caused by ingest because I replicated it with ingest none. A bit more info about the bug, in the dmesg you could see:
`[mié jun 15 11:59:27 2016] traps: python[367] trap int3 ip:7f6fa22759eb sp:7f6ee1924720 error:0
`
And it happens when a scheduled recording stops (but only a few times not in all scheduled recordings)
And when this bug happens, after stop the recording in the preview you can see a white screen and the state initializing before galicaster crash.

**Comment by hcaloto** [comment] 2016-07-01 11:12
It should be solved with https://github.com/teltek/Galicaster/commit/089a3a4ca2ab1ceba5e2122280723a87bdc91dc0 and https://github.com/teltek/Galicaster/commit/85db8131fc7af5b004eafbd788269d0a75098f8c

**Comment by silviabf** [comment] 2016-08-01 14:08
After more than 200 scheduled recordings, i could not replicate this bug again. I close this issue. @smarquard feel free to open it again if you can replicate it, thanks!.

**Closed by silviabf** 2016-08-01 14:08 UTC
Labels: P3: important, ReadyforQA, stability issue
