### ISSUE TITLE
There is a cross in the center of recorded screen video.

### ISSUE THREAD

**Issue by fishfree** [teltek/Galicaster#327] opened 2016-06-22 02:29 UTC
I have 2 screens connected to my GA box, I record PPT from one screen. But in the center of the recorded video, there is an ugly cross icon on top of it as the screenshot below.
![gacross](https://cloud.githubusercontent.com/assets/1741341/16252858/3ed3e272-3864-11e6-90fc-bbd2d6a17b74.png)

**Comment by hcaloto** [comment] 2016-06-22 08:31
Hi, It seems like it is introduced by some external element, since Galicaster puts nothing over the video input.

**Comment by bleedinge** [comment] 2016-06-28 08:10
I'm closing this as we can't reproduce it without help of the OP.

If this happens again and you can tell us how to replicate it, being Galicaster the cause, we will happily work on it.

**Closed by bleedinge** 2016-06-28 08:10 UTC
Labels: question

**Comment by fishfree** [comment] 2016-06-30 22:54
I use dual screen and screen capture feature of Galicaster, there is always a cross icon on the screen capture video. So please reopen this issue and fix the bug.
