### ISSUE TITLE
Blurry / fuzzy webcam on first startup of GC 2 beta

### ISSUE THREAD

**Issue by Kirk-LCF** [teltek/Galicaster#381] opened 2016-07-29 14:32 UTC
On first startup of GC the Webcam (Logitec C270) gives a fuzzy image. Shutdown GC and restart
corrects this. See attached Image.

![bluryy webcam](https://cloud.githubusercontent.com/assets/20046917/17251590/5a839620-55a1-11e6-9e33-15bd6fc55418.png)

**Comment by Alfro** [comment] 2016-11-21 15:37
@Kirk-LCF We couldn't reproduce this bug. Is it still happening on the current 2.0.x branch?

**Comment by Alfro** [comment] 2018-08-27 11:53
This issue is 2 years old. I'm closing it, but if this is happening to anyone please feel free to reopen it.

**Closed by Alfro** 2018-08-27 11:53 UTC
Labels: bug, question
